apiVersion: apps/v1
kind: Deployment
metadata:
  name: retailpulse-app
  namespace: retailpulse

spec:
  replicas: 2

  selector:
    matchLabels:
      app: retailpulse

  template:
    metadata:
      labels:
        app: retailpulse

    spec:
      containers:
      - name: retailpulse
        image: saibalajijammu/retailpulse:latest

        ports:
        - containerPort: 8501

        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"

          limits:
            memory: "1Gi"
            cpu: "1"